/*
 * generated by Xtext 2.20.0
 */
package org.xtext.json.schema;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Draft7RuntimeModule extends AbstractDraft7RuntimeModule {
}
