/**
 * generated by Xtext 2.20.0
 */
package org.xtext.json.schema.draft7.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.json.schema.draft7.Draft7Package;
import org.xtext.json.schema.draft7.ExclusiveMinimum;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exclusive Minimum</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.json.schema.draft7.impl.ExclusiveMinimumImpl#getExclusiveMinimum <em>Exclusive Minimum</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExclusiveMinimumImpl extends MinimalEObjectImpl.Container implements ExclusiveMinimum
{
  /**
   * The default value of the '{@link #getExclusiveMinimum() <em>Exclusive Minimum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExclusiveMinimum()
   * @generated
   * @ordered
   */
  protected static final int EXCLUSIVE_MINIMUM_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getExclusiveMinimum() <em>Exclusive Minimum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExclusiveMinimum()
   * @generated
   * @ordered
   */
  protected int exclusiveMinimum = EXCLUSIVE_MINIMUM_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExclusiveMinimumImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Draft7Package.Literals.EXCLUSIVE_MINIMUM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getExclusiveMinimum()
  {
    return exclusiveMinimum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExclusiveMinimum(int newExclusiveMinimum)
  {
    int oldExclusiveMinimum = exclusiveMinimum;
    exclusiveMinimum = newExclusiveMinimum;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Draft7Package.EXCLUSIVE_MINIMUM__EXCLUSIVE_MINIMUM, oldExclusiveMinimum, exclusiveMinimum));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Draft7Package.EXCLUSIVE_MINIMUM__EXCLUSIVE_MINIMUM:
        return getExclusiveMinimum();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Draft7Package.EXCLUSIVE_MINIMUM__EXCLUSIVE_MINIMUM:
        setExclusiveMinimum((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Draft7Package.EXCLUSIVE_MINIMUM__EXCLUSIVE_MINIMUM:
        setExclusiveMinimum(EXCLUSIVE_MINIMUM_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Draft7Package.EXCLUSIVE_MINIMUM__EXCLUSIVE_MINIMUM:
        return exclusiveMinimum != EXCLUSIVE_MINIMUM_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (exclusiveMinimum: ");
    result.append(exclusiveMinimum);
    result.append(')');
    return result.toString();
  }

} //ExclusiveMinimumImpl
