/**
 * generated by Xtext 2.20.0
 */
package org.xtext.json.schema.draft7.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.json.schema.draft7.Draft7Package;
import org.xtext.json.schema.draft7.ObjectProperties;
import org.xtext.json.schema.draft7.Properties;
import org.xtext.json.schema.draft7.RequiredProperties;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Object Properties</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.json.schema.draft7.impl.ObjectPropertiesImpl#getProperties <em>Properties</em>}</li>
 *   <li>{@link org.xtext.json.schema.draft7.impl.ObjectPropertiesImpl#getRequiredProperties <em>Required Properties</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ObjectPropertiesImpl extends JsonSchemaRootImpl implements ObjectProperties
{
  /**
   * The cached value of the '{@link #getProperties() <em>Properties</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProperties()
   * @generated
   * @ordered
   */
  protected Properties properties;

  /**
   * The cached value of the '{@link #getRequiredProperties() <em>Required Properties</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRequiredProperties()
   * @generated
   * @ordered
   */
  protected RequiredProperties requiredProperties;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ObjectPropertiesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Draft7Package.Literals.OBJECT_PROPERTIES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Properties getProperties()
  {
    return properties;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetProperties(Properties newProperties, NotificationChain msgs)
  {
    Properties oldProperties = properties;
    properties = newProperties;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Draft7Package.OBJECT_PROPERTIES__PROPERTIES, oldProperties, newProperties);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setProperties(Properties newProperties)
  {
    if (newProperties != properties)
    {
      NotificationChain msgs = null;
      if (properties != null)
        msgs = ((InternalEObject)properties).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - Draft7Package.OBJECT_PROPERTIES__PROPERTIES, null, msgs);
      if (newProperties != null)
        msgs = ((InternalEObject)newProperties).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - Draft7Package.OBJECT_PROPERTIES__PROPERTIES, null, msgs);
      msgs = basicSetProperties(newProperties, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Draft7Package.OBJECT_PROPERTIES__PROPERTIES, newProperties, newProperties));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RequiredProperties getRequiredProperties()
  {
    return requiredProperties;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRequiredProperties(RequiredProperties newRequiredProperties, NotificationChain msgs)
  {
    RequiredProperties oldRequiredProperties = requiredProperties;
    requiredProperties = newRequiredProperties;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Draft7Package.OBJECT_PROPERTIES__REQUIRED_PROPERTIES, oldRequiredProperties, newRequiredProperties);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRequiredProperties(RequiredProperties newRequiredProperties)
  {
    if (newRequiredProperties != requiredProperties)
    {
      NotificationChain msgs = null;
      if (requiredProperties != null)
        msgs = ((InternalEObject)requiredProperties).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - Draft7Package.OBJECT_PROPERTIES__REQUIRED_PROPERTIES, null, msgs);
      if (newRequiredProperties != null)
        msgs = ((InternalEObject)newRequiredProperties).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - Draft7Package.OBJECT_PROPERTIES__REQUIRED_PROPERTIES, null, msgs);
      msgs = basicSetRequiredProperties(newRequiredProperties, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Draft7Package.OBJECT_PROPERTIES__REQUIRED_PROPERTIES, newRequiredProperties, newRequiredProperties));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case Draft7Package.OBJECT_PROPERTIES__PROPERTIES:
        return basicSetProperties(null, msgs);
      case Draft7Package.OBJECT_PROPERTIES__REQUIRED_PROPERTIES:
        return basicSetRequiredProperties(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Draft7Package.OBJECT_PROPERTIES__PROPERTIES:
        return getProperties();
      case Draft7Package.OBJECT_PROPERTIES__REQUIRED_PROPERTIES:
        return getRequiredProperties();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Draft7Package.OBJECT_PROPERTIES__PROPERTIES:
        setProperties((Properties)newValue);
        return;
      case Draft7Package.OBJECT_PROPERTIES__REQUIRED_PROPERTIES:
        setRequiredProperties((RequiredProperties)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Draft7Package.OBJECT_PROPERTIES__PROPERTIES:
        setProperties((Properties)null);
        return;
      case Draft7Package.OBJECT_PROPERTIES__REQUIRED_PROPERTIES:
        setRequiredProperties((RequiredProperties)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Draft7Package.OBJECT_PROPERTIES__PROPERTIES:
        return properties != null;
      case Draft7Package.OBJECT_PROPERTIES__REQUIRED_PROPERTIES:
        return requiredProperties != null;
    }
    return super.eIsSet(featureID);
  }

} //ObjectPropertiesImpl
