/**
 * generated by Xtext 2.20.0
 */
package org.xtext.json.schema.draft7.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.json.schema.draft7.Draft7Package;
import org.xtext.json.schema.draft7.RequiredProperties;
import org.xtext.json.schema.draft7.RequiredPropertiesName;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Required Properties</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.json.schema.draft7.impl.RequiredPropertiesImpl#getRequiredProperties <em>Required Properties</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RequiredPropertiesImpl extends MinimalEObjectImpl.Container implements RequiredProperties
{
  /**
   * The cached value of the '{@link #getRequiredProperties() <em>Required Properties</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRequiredProperties()
   * @generated
   * @ordered
   */
  protected EList<RequiredPropertiesName> requiredProperties;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RequiredPropertiesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Draft7Package.Literals.REQUIRED_PROPERTIES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<RequiredPropertiesName> getRequiredProperties()
  {
    if (requiredProperties == null)
    {
      requiredProperties = new EObjectContainmentEList<RequiredPropertiesName>(RequiredPropertiesName.class, this, Draft7Package.REQUIRED_PROPERTIES__REQUIRED_PROPERTIES);
    }
    return requiredProperties;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case Draft7Package.REQUIRED_PROPERTIES__REQUIRED_PROPERTIES:
        return ((InternalEList<?>)getRequiredProperties()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Draft7Package.REQUIRED_PROPERTIES__REQUIRED_PROPERTIES:
        return getRequiredProperties();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Draft7Package.REQUIRED_PROPERTIES__REQUIRED_PROPERTIES:
        getRequiredProperties().clear();
        getRequiredProperties().addAll((Collection<? extends RequiredPropertiesName>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Draft7Package.REQUIRED_PROPERTIES__REQUIRED_PROPERTIES:
        getRequiredProperties().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Draft7Package.REQUIRED_PROPERTIES__REQUIRED_PROPERTIES:
        return requiredProperties != null && !requiredProperties.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //RequiredPropertiesImpl
