/*
 * generated by Xtext 2.20.0
 */
package org.xtext.json.schema.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.json.schema.ui.internal.SchemaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Draft7ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(SchemaActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		SchemaActivator activator = SchemaActivator.getInstance();
		return activator != null ? activator.getInjector(SchemaActivator.ORG_XTEXT_JSON_SCHEMA_DRAFT7) : null;
	}

}
