/*
 * generated by Xtext 2.20.0
 */
package org.xtext.json.schema.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.json.schema.parser.antlr.internal.InternalDraft7Parser;
import org.xtext.json.schema.services.Draft7GrammarAccess;

public class Draft7Parser extends AbstractAntlrParser {

	@Inject
	private Draft7GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDraft7Parser createParser(XtextTokenStream stream) {
		return new InternalDraft7Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public Draft7GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Draft7GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
