/*
 * generated by Xtext 2.20.0
 */
package org.xtext.json.schema.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Draft7AntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/json/schema/parser/antlr/internal/InternalDraft7.tokens");
	}
}
