/*
 * generated by Xtext 2.20.0
 */
package org.xtext.json.schema.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractDraft7Validator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.json.schema.draft7.Draft7Package.eINSTANCE);
		return result;
	}
}
