/*
 * generated by Xtext 2.20.0
 */
package org.xtext.json.schema.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDraft7ScopeProvider extends DelegatingScopeProvider {
}
