/**
 * generated by Xtext 2.20.0
 */
package org.xtext.json.schema.generator;

import com.google.common.collect.Iterators;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.StringExtensions;
import org.xtext.json.schema.draft7.AbstractSchema;
import org.xtext.json.schema.draft7.NamedSchema;
import org.xtext.json.schema.draft7.Reference;
import org.xtext.json.schema.draft7.Schema;
import org.xtext.json.schema.generator.BuilderGenerator;
import org.xtext.json.schema.generator.CustomModel;
import org.xtext.json.schema.generator.GeneratorUtils;
import org.xtext.json.schema.generator.ModelGenerator;
import org.xtext.json.schema.generator.RootBuilderGenerator;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class Draft7Generator extends AbstractGenerator {
  private Schema root;
  
  private List<CustomModel> objectList;
  
  private ModelGenerator modelGenerator;
  
  private RootBuilderGenerator rootBuilderGenerator;
  
  private BuilderGenerator builderGenerator;
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    ArrayList<CustomModel> _arrayList = new ArrayList<CustomModel>();
    this.objectList = _arrayList;
    this.root = Iterators.<Schema>filter(resource.getAllContents(), Schema.class).next();
    String _xifexpression = null;
    String _title = this.root.getTitle();
    boolean _tripleNotEquals = (_title != null);
    if (_tripleNotEquals) {
      _xifexpression = StringExtensions.toFirstUpper(this.root.getTitle().replace(" ", "").replace(".", ""));
    } else {
      _xifexpression = "root";
    }
    String rootname = _xifexpression;
    CustomModel _customModel = new CustomModel(this.root, rootname);
    this.objectList.add(_customModel);
    this.recursiveObjectsFinder(this.root.getProperties(), rootname);
    this.recursiveObjectsFinder(this.root.getDefinitions(), rootname);
    ModelGenerator _modelGenerator = new ModelGenerator(this.objectList, this.root);
    this.modelGenerator = _modelGenerator;
    RootBuilderGenerator _rootBuilderGenerator = new RootBuilderGenerator(this.objectList, this.root);
    this.rootBuilderGenerator = _rootBuilderGenerator;
    BuilderGenerator _builderGenerator = new BuilderGenerator(this.objectList, this.root);
    this.builderGenerator = _builderGenerator;
    final Consumer<CustomModel> _function = (CustomModel model) -> {
      this.modelGenerator.generateModelFile(model, fsa);
      this.builderGenerator.generateBuilderFile(model, fsa);
      this.rootBuilderGenerator.generateBuilderFile(model, fsa);
    };
    this.objectList.forEach(_function);
    System.out.println(this.objectList.size());
  }
  
  public void recursiveObjectsFinder(final List<NamedSchema> properties, final String parentName) {
    final Consumer<NamedSchema> _function = (NamedSchema property) -> {
      AbstractSchema propSchema = property.getSchema();
      Schema _xifexpression = null;
      boolean _isSchema = GeneratorUtils.isSchema(propSchema);
      if (_isSchema) {
        _xifexpression = ((Schema) propSchema);
      } else {
        _xifexpression = GeneratorUtils.findLocalReference(GeneratorUtils.realizeName(((Reference) propSchema).getUri()), this.root);
      }
      Schema schema = _xifexpression;
      String propName = GeneratorUtils.realizeName(property.getName());
      boolean _equals = propName.equals("schema");
      if (_equals) {
        System.out.println(this.objectList.size());
      }
      if ((((schema != null) && (!GeneratorUtils.realizeName(property.getName()).toLowerCase().equals(parentName.toLowerCase()))) && (!this.walkedThroughDefinition.contains(propName)))) {
        boolean _isObject = GeneratorUtils.isObject(schema);
        if (_isObject) {
          final CustomModel cm = new CustomModel(schema, propName);
          cm.setParentName(parentName);
          this.objectList.add(cm);
          this.walkedThroughDefinition.add(GeneratorUtils.realizeName(property.getName()));
          this.recursiveObjectsFinder(schema.getProperties(), propName);
        }
        if (((schema.getAnyOfs() != null) && (!schema.getAnyOfs().isEmpty()))) {
          final CustomModel cm_1 = new CustomModel(schema, propName);
          cm_1.setParentName(parentName);
          this.objectList.add(cm_1);
          this.walkedThroughDefinition.add(GeneratorUtils.realizeName(property.getName()));
          this.complexityObjectsFinder(schema.getAnyOfs(), propName);
        }
        if (((schema.getOneOfs() != null) && (!schema.getOneOfs().isEmpty()))) {
          final CustomModel cm_2 = new CustomModel(schema, propName);
          cm_2.setParentName(parentName);
          this.objectList.add(cm_2);
          this.walkedThroughDefinition.add(GeneratorUtils.realizeName(property.getName()));
          this.complexityObjectsFinder(schema.getOneOfs(), propName);
        }
        if (((schema.getAllOfs() != null) && (!schema.getAllOfs().isEmpty()))) {
          final CustomModel cm_3 = new CustomModel(schema, propName);
          cm_3.setParentName(parentName);
          this.objectList.add(cm_3);
          this.walkedThroughDefinition.add(GeneratorUtils.realizeName(property.getName()));
          this.complexityObjectsFinder(schema.getAllOfs(), propName);
        }
      }
    };
    properties.forEach(_function);
  }
  
  private List<String> walkedThroughDefinition = new ArrayList<String>();
  
  private List<AbstractSchema> currentNestedSchemas = new ArrayList<AbstractSchema>();
  
  public void complexityObjectsFinder(final List<AbstractSchema> schemas, final String parentName) {
    final Consumer<AbstractSchema> _function = (AbstractSchema abstractSchema) -> {
      Schema _xifexpression = null;
      boolean _isSchema = GeneratorUtils.isSchema(abstractSchema);
      if (_isSchema) {
        _xifexpression = ((Schema) abstractSchema);
      } else {
        _xifexpression = GeneratorUtils.findLocalReference(GeneratorUtils.realizeName(((Reference) abstractSchema).getUri()), this.root);
      }
      Schema schema = _xifexpression;
      if (((schema != null) && (!this.currentNestedSchemas.contains(abstractSchema)))) {
        this.currentNestedSchemas.add(abstractSchema);
        boolean _isObject = GeneratorUtils.isObject(schema);
        if (_isObject) {
          this.recursiveObjectsFinder(schema.getProperties(), parentName);
        }
        if (((schema.getAnyOfs() != null) && (!schema.getAnyOfs().isEmpty()))) {
          this.complexityObjectsFinder(schema.getAnyOfs(), parentName);
        }
        if (((schema.getOneOfs() != null) && (!schema.getOneOfs().isEmpty()))) {
          this.complexityObjectsFinder(schema.getOneOfs(), parentName);
        }
        if (((schema.getAllOfs() != null) && (!schema.getAllOfs().isEmpty()))) {
          this.complexityObjectsFinder(schema.getAllOfs(), parentName);
        }
      }
    };
    schemas.forEach(_function);
  }
}
