/**
 * generated by Xtext 2.20.0
 */
package org.xtext.json.schema.draft7;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.json.schema.draft7.Draft7Factory
 * @model kind="package"
 * @generated
 */
public interface Draft7Package extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "draft7";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/json/schema/Draft7";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "draft7";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Draft7Package eINSTANCE = org.xtext.json.schema.draft7.impl.Draft7PackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.json.schema.draft7.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.json.schema.draft7.impl.ModelImpl
   * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Root</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ROOT = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.json.schema.draft7.impl.JsonSchemaRootImpl <em>Json Schema Root</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.json.schema.draft7.impl.JsonSchemaRootImpl
   * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getJsonSchemaRoot()
   * @generated
   */
  int JSON_SCHEMA_ROOT = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_SCHEMA_ROOT__TYPE = 0;

  /**
   * The number of structural features of the '<em>Json Schema Root</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_SCHEMA_ROOT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.json.schema.draft7.impl.NumberPropertiesImpl <em>Number Properties</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.json.schema.draft7.impl.NumberPropertiesImpl
   * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getNumberProperties()
   * @generated
   */
  int NUMBER_PROPERTIES = 2;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_PROPERTIES__TYPE = JSON_SCHEMA_ROOT__TYPE;

  /**
   * The feature id for the '<em><b>Minimum</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_PROPERTIES__MINIMUM = JSON_SCHEMA_ROOT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Exclusive Minimum</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_PROPERTIES__EXCLUSIVE_MINIMUM = JSON_SCHEMA_ROOT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Maximum</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_PROPERTIES__MAXIMUM = JSON_SCHEMA_ROOT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Exclusive Maximum</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_PROPERTIES__EXCLUSIVE_MAXIMUM = JSON_SCHEMA_ROOT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Number Properties</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_PROPERTIES_FEATURE_COUNT = JSON_SCHEMA_ROOT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.json.schema.draft7.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.json.schema.draft7.impl.TypeImpl
   * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getType()
   * @generated
   */
  int TYPE = 3;

  /**
   * The feature id for the '<em><b>Types</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__TYPES = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__TYPE = 1;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.json.schema.draft7.impl.ObjectPropertiesImpl <em>Object Properties</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.json.schema.draft7.impl.ObjectPropertiesImpl
   * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getObjectProperties()
   * @generated
   */
  int OBJECT_PROPERTIES = 4;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_PROPERTIES__TYPE = JSON_SCHEMA_ROOT__TYPE;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_PROPERTIES__PROPERTIES = JSON_SCHEMA_ROOT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Required Properties</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_PROPERTIES__REQUIRED_PROPERTIES = JSON_SCHEMA_ROOT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Object Properties</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_PROPERTIES_FEATURE_COUNT = JSON_SCHEMA_ROOT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.json.schema.draft7.impl.RequiredPropertiesImpl <em>Required Properties</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.json.schema.draft7.impl.RequiredPropertiesImpl
   * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getRequiredProperties()
   * @generated
   */
  int REQUIRED_PROPERTIES = 5;

  /**
   * The feature id for the '<em><b>Required Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIRED_PROPERTIES__REQUIRED_PROPERTIES = 0;

  /**
   * The number of structural features of the '<em>Required Properties</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIRED_PROPERTIES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.json.schema.draft7.impl.RequiredPropertiesNameImpl <em>Required Properties Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.json.schema.draft7.impl.RequiredPropertiesNameImpl
   * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getRequiredPropertiesName()
   * @generated
   */
  int REQUIRED_PROPERTIES_NAME = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIRED_PROPERTIES_NAME__NAME = 0;

  /**
   * The number of structural features of the '<em>Required Properties Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIRED_PROPERTIES_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.json.schema.draft7.impl.PropertiesImpl <em>Properties</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.json.schema.draft7.impl.PropertiesImpl
   * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getProperties()
   * @generated
   */
  int PROPERTIES = 7;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTIES__PROPERTIES = 0;

  /**
   * The number of structural features of the '<em>Properties</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTIES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.json.schema.draft7.impl.PropertyImpl <em>Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.json.schema.draft7.impl.PropertyImpl
   * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getProperty()
   * @generated
   */
  int PROPERTY = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__NAME = 0;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__PROPERTIES = 1;

  /**
   * The number of structural features of the '<em>Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.json.schema.draft7.impl.StringPropertiesImpl <em>String Properties</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.json.schema.draft7.impl.StringPropertiesImpl
   * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getStringProperties()
   * @generated
   */
  int STRING_PROPERTIES = 9;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_PROPERTIES__TYPE = JSON_SCHEMA_ROOT__TYPE;

  /**
   * The feature id for the '<em><b>Length</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_PROPERTIES__LENGTH = JSON_SCHEMA_ROOT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Pattern</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_PROPERTIES__PATTERN = JSON_SCHEMA_ROOT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>String Properties</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_PROPERTIES_FEATURE_COUNT = JSON_SCHEMA_ROOT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.json.schema.draft7.impl.LengthImpl <em>Length</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.json.schema.draft7.impl.LengthImpl
   * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getLength()
   * @generated
   */
  int LENGTH = 10;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LENGTH__LENGTH = 0;

  /**
   * The number of structural features of the '<em>Length</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LENGTH_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.json.schema.draft7.impl.PatternImpl <em>Pattern</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.json.schema.draft7.impl.PatternImpl
   * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getPattern()
   * @generated
   */
  int PATTERN = 11;

  /**
   * The feature id for the '<em><b>Pattern</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN__PATTERN = 0;

  /**
   * The number of structural features of the '<em>Pattern</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.json.schema.draft7.impl.MultiplesImpl <em>Multiples</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.json.schema.draft7.impl.MultiplesImpl
   * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getMultiples()
   * @generated
   */
  int MULTIPLES = 12;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLES__TYPE = NUMBER_PROPERTIES__TYPE;

  /**
   * The feature id for the '<em><b>Minimum</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLES__MINIMUM = NUMBER_PROPERTIES__MINIMUM;

  /**
   * The feature id for the '<em><b>Exclusive Minimum</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLES__EXCLUSIVE_MINIMUM = NUMBER_PROPERTIES__EXCLUSIVE_MINIMUM;

  /**
   * The feature id for the '<em><b>Maximum</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLES__MAXIMUM = NUMBER_PROPERTIES__MAXIMUM;

  /**
   * The feature id for the '<em><b>Exclusive Maximum</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLES__EXCLUSIVE_MAXIMUM = NUMBER_PROPERTIES__EXCLUSIVE_MAXIMUM;

  /**
   * The feature id for the '<em><b>Multiple Of</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLES__MULTIPLE_OF = NUMBER_PROPERTIES_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Multiples</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLES_FEATURE_COUNT = NUMBER_PROPERTIES_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.json.schema.draft7.impl.MinimumImpl <em>Minimum</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.json.schema.draft7.impl.MinimumImpl
   * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getMinimum()
   * @generated
   */
  int MINIMUM = 13;

  /**
   * The feature id for the '<em><b>Minimum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINIMUM__MINIMUM = 0;

  /**
   * The number of structural features of the '<em>Minimum</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINIMUM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.json.schema.draft7.impl.ExclusiveMinimumImpl <em>Exclusive Minimum</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.json.schema.draft7.impl.ExclusiveMinimumImpl
   * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getExclusiveMinimum()
   * @generated
   */
  int EXCLUSIVE_MINIMUM = 14;

  /**
   * The feature id for the '<em><b>Exclusive Minimum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXCLUSIVE_MINIMUM__EXCLUSIVE_MINIMUM = 0;

  /**
   * The number of structural features of the '<em>Exclusive Minimum</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXCLUSIVE_MINIMUM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.json.schema.draft7.impl.MaximumImpl <em>Maximum</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.json.schema.draft7.impl.MaximumImpl
   * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getMaximum()
   * @generated
   */
  int MAXIMUM = 15;

  /**
   * The feature id for the '<em><b>Maximum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAXIMUM__MAXIMUM = 0;

  /**
   * The number of structural features of the '<em>Maximum</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAXIMUM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.json.schema.draft7.impl.ExclusiveMaximumImpl <em>Exclusive Maximum</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.json.schema.draft7.impl.ExclusiveMaximumImpl
   * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getExclusiveMaximum()
   * @generated
   */
  int EXCLUSIVE_MAXIMUM = 16;

  /**
   * The feature id for the '<em><b>Exclusive Maximum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXCLUSIVE_MAXIMUM__EXCLUSIVE_MAXIMUM = 0;

  /**
   * The number of structural features of the '<em>Exclusive Maximum</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXCLUSIVE_MAXIMUM_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.json.schema.draft7.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.json.schema.draft7.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.json.schema.draft7.Model#getRoot <em>Root</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Root</em>'.
   * @see org.xtext.json.schema.draft7.Model#getRoot()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Root();

  /**
   * Returns the meta object for class '{@link org.xtext.json.schema.draft7.JsonSchemaRoot <em>Json Schema Root</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json Schema Root</em>'.
   * @see org.xtext.json.schema.draft7.JsonSchemaRoot
   * @generated
   */
  EClass getJsonSchemaRoot();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.json.schema.draft7.JsonSchemaRoot#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.json.schema.draft7.JsonSchemaRoot#getType()
   * @see #getJsonSchemaRoot()
   * @generated
   */
  EReference getJsonSchemaRoot_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.json.schema.draft7.NumberProperties <em>Number Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number Properties</em>'.
   * @see org.xtext.json.schema.draft7.NumberProperties
   * @generated
   */
  EClass getNumberProperties();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.json.schema.draft7.NumberProperties#getMinimum <em>Minimum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Minimum</em>'.
   * @see org.xtext.json.schema.draft7.NumberProperties#getMinimum()
   * @see #getNumberProperties()
   * @generated
   */
  EReference getNumberProperties_Minimum();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.json.schema.draft7.NumberProperties#getExclusiveMinimum <em>Exclusive Minimum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exclusive Minimum</em>'.
   * @see org.xtext.json.schema.draft7.NumberProperties#getExclusiveMinimum()
   * @see #getNumberProperties()
   * @generated
   */
  EReference getNumberProperties_ExclusiveMinimum();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.json.schema.draft7.NumberProperties#getMaximum <em>Maximum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Maximum</em>'.
   * @see org.xtext.json.schema.draft7.NumberProperties#getMaximum()
   * @see #getNumberProperties()
   * @generated
   */
  EReference getNumberProperties_Maximum();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.json.schema.draft7.NumberProperties#getExclusiveMaximum <em>Exclusive Maximum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exclusive Maximum</em>'.
   * @see org.xtext.json.schema.draft7.NumberProperties#getExclusiveMaximum()
   * @see #getNumberProperties()
   * @generated
   */
  EReference getNumberProperties_ExclusiveMaximum();

  /**
   * Returns the meta object for class '{@link org.xtext.json.schema.draft7.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.xtext.json.schema.draft7.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.json.schema.draft7.Type#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Types</em>'.
   * @see org.xtext.json.schema.draft7.Type#getTypes()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Types();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.json.schema.draft7.Type#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.json.schema.draft7.Type#getType()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.json.schema.draft7.ObjectProperties <em>Object Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object Properties</em>'.
   * @see org.xtext.json.schema.draft7.ObjectProperties
   * @generated
   */
  EClass getObjectProperties();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.json.schema.draft7.ObjectProperties#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Properties</em>'.
   * @see org.xtext.json.schema.draft7.ObjectProperties#getProperties()
   * @see #getObjectProperties()
   * @generated
   */
  EReference getObjectProperties_Properties();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.json.schema.draft7.ObjectProperties#getRequiredProperties <em>Required Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Required Properties</em>'.
   * @see org.xtext.json.schema.draft7.ObjectProperties#getRequiredProperties()
   * @see #getObjectProperties()
   * @generated
   */
  EReference getObjectProperties_RequiredProperties();

  /**
   * Returns the meta object for class '{@link org.xtext.json.schema.draft7.RequiredProperties <em>Required Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Required Properties</em>'.
   * @see org.xtext.json.schema.draft7.RequiredProperties
   * @generated
   */
  EClass getRequiredProperties();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.json.schema.draft7.RequiredProperties#getRequiredProperties <em>Required Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Required Properties</em>'.
   * @see org.xtext.json.schema.draft7.RequiredProperties#getRequiredProperties()
   * @see #getRequiredProperties()
   * @generated
   */
  EReference getRequiredProperties_RequiredProperties();

  /**
   * Returns the meta object for class '{@link org.xtext.json.schema.draft7.RequiredPropertiesName <em>Required Properties Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Required Properties Name</em>'.
   * @see org.xtext.json.schema.draft7.RequiredPropertiesName
   * @generated
   */
  EClass getRequiredPropertiesName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.json.schema.draft7.RequiredPropertiesName#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.json.schema.draft7.RequiredPropertiesName#getName()
   * @see #getRequiredPropertiesName()
   * @generated
   */
  EAttribute getRequiredPropertiesName_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.json.schema.draft7.Properties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Properties</em>'.
   * @see org.xtext.json.schema.draft7.Properties
   * @generated
   */
  EClass getProperties();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.json.schema.draft7.Properties#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see org.xtext.json.schema.draft7.Properties#getProperties()
   * @see #getProperties()
   * @generated
   */
  EReference getProperties_Properties();

  /**
   * Returns the meta object for class '{@link org.xtext.json.schema.draft7.Property <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property</em>'.
   * @see org.xtext.json.schema.draft7.Property
   * @generated
   */
  EClass getProperty();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.json.schema.draft7.Property#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.json.schema.draft7.Property#getName()
   * @see #getProperty()
   * @generated
   */
  EAttribute getProperty_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.json.schema.draft7.Property#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see org.xtext.json.schema.draft7.Property#getProperties()
   * @see #getProperty()
   * @generated
   */
  EReference getProperty_Properties();

  /**
   * Returns the meta object for class '{@link org.xtext.json.schema.draft7.StringProperties <em>String Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Properties</em>'.
   * @see org.xtext.json.schema.draft7.StringProperties
   * @generated
   */
  EClass getStringProperties();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.json.schema.draft7.StringProperties#getLength <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Length</em>'.
   * @see org.xtext.json.schema.draft7.StringProperties#getLength()
   * @see #getStringProperties()
   * @generated
   */
  EReference getStringProperties_Length();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.json.schema.draft7.StringProperties#getPattern <em>Pattern</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pattern</em>'.
   * @see org.xtext.json.schema.draft7.StringProperties#getPattern()
   * @see #getStringProperties()
   * @generated
   */
  EReference getStringProperties_Pattern();

  /**
   * Returns the meta object for class '{@link org.xtext.json.schema.draft7.Length <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Length</em>'.
   * @see org.xtext.json.schema.draft7.Length
   * @generated
   */
  EClass getLength();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.json.schema.draft7.Length#getLength <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Length</em>'.
   * @see org.xtext.json.schema.draft7.Length#getLength()
   * @see #getLength()
   * @generated
   */
  EAttribute getLength_Length();

  /**
   * Returns the meta object for class '{@link org.xtext.json.schema.draft7.Pattern <em>Pattern</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pattern</em>'.
   * @see org.xtext.json.schema.draft7.Pattern
   * @generated
   */
  EClass getPattern();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.json.schema.draft7.Pattern#getPattern <em>Pattern</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pattern</em>'.
   * @see org.xtext.json.schema.draft7.Pattern#getPattern()
   * @see #getPattern()
   * @generated
   */
  EAttribute getPattern_Pattern();

  /**
   * Returns the meta object for class '{@link org.xtext.json.schema.draft7.Multiples <em>Multiples</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiples</em>'.
   * @see org.xtext.json.schema.draft7.Multiples
   * @generated
   */
  EClass getMultiples();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.json.schema.draft7.Multiples#getMultipleOf <em>Multiple Of</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Multiple Of</em>'.
   * @see org.xtext.json.schema.draft7.Multiples#getMultipleOf()
   * @see #getMultiples()
   * @generated
   */
  EAttribute getMultiples_MultipleOf();

  /**
   * Returns the meta object for class '{@link org.xtext.json.schema.draft7.Minimum <em>Minimum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Minimum</em>'.
   * @see org.xtext.json.schema.draft7.Minimum
   * @generated
   */
  EClass getMinimum();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.json.schema.draft7.Minimum#getMinimum <em>Minimum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Minimum</em>'.
   * @see org.xtext.json.schema.draft7.Minimum#getMinimum()
   * @see #getMinimum()
   * @generated
   */
  EAttribute getMinimum_Minimum();

  /**
   * Returns the meta object for class '{@link org.xtext.json.schema.draft7.ExclusiveMinimum <em>Exclusive Minimum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exclusive Minimum</em>'.
   * @see org.xtext.json.schema.draft7.ExclusiveMinimum
   * @generated
   */
  EClass getExclusiveMinimum();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.json.schema.draft7.ExclusiveMinimum#getExclusiveMinimum <em>Exclusive Minimum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Exclusive Minimum</em>'.
   * @see org.xtext.json.schema.draft7.ExclusiveMinimum#getExclusiveMinimum()
   * @see #getExclusiveMinimum()
   * @generated
   */
  EAttribute getExclusiveMinimum_ExclusiveMinimum();

  /**
   * Returns the meta object for class '{@link org.xtext.json.schema.draft7.Maximum <em>Maximum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Maximum</em>'.
   * @see org.xtext.json.schema.draft7.Maximum
   * @generated
   */
  EClass getMaximum();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.json.schema.draft7.Maximum#getMaximum <em>Maximum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Maximum</em>'.
   * @see org.xtext.json.schema.draft7.Maximum#getMaximum()
   * @see #getMaximum()
   * @generated
   */
  EAttribute getMaximum_Maximum();

  /**
   * Returns the meta object for class '{@link org.xtext.json.schema.draft7.ExclusiveMaximum <em>Exclusive Maximum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exclusive Maximum</em>'.
   * @see org.xtext.json.schema.draft7.ExclusiveMaximum
   * @generated
   */
  EClass getExclusiveMaximum();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.json.schema.draft7.ExclusiveMaximum#getExclusiveMaximum <em>Exclusive Maximum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Exclusive Maximum</em>'.
   * @see org.xtext.json.schema.draft7.ExclusiveMaximum#getExclusiveMaximum()
   * @see #getExclusiveMaximum()
   * @generated
   */
  EAttribute getExclusiveMaximum_ExclusiveMaximum();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  Draft7Factory getDraft7Factory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.json.schema.draft7.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.json.schema.draft7.impl.ModelImpl
     * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Root</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ROOT = eINSTANCE.getModel_Root();

    /**
     * The meta object literal for the '{@link org.xtext.json.schema.draft7.impl.JsonSchemaRootImpl <em>Json Schema Root</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.json.schema.draft7.impl.JsonSchemaRootImpl
     * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getJsonSchemaRoot()
     * @generated
     */
    EClass JSON_SCHEMA_ROOT = eINSTANCE.getJsonSchemaRoot();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_SCHEMA_ROOT__TYPE = eINSTANCE.getJsonSchemaRoot_Type();

    /**
     * The meta object literal for the '{@link org.xtext.json.schema.draft7.impl.NumberPropertiesImpl <em>Number Properties</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.json.schema.draft7.impl.NumberPropertiesImpl
     * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getNumberProperties()
     * @generated
     */
    EClass NUMBER_PROPERTIES = eINSTANCE.getNumberProperties();

    /**
     * The meta object literal for the '<em><b>Minimum</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NUMBER_PROPERTIES__MINIMUM = eINSTANCE.getNumberProperties_Minimum();

    /**
     * The meta object literal for the '<em><b>Exclusive Minimum</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NUMBER_PROPERTIES__EXCLUSIVE_MINIMUM = eINSTANCE.getNumberProperties_ExclusiveMinimum();

    /**
     * The meta object literal for the '<em><b>Maximum</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NUMBER_PROPERTIES__MAXIMUM = eINSTANCE.getNumberProperties_Maximum();

    /**
     * The meta object literal for the '<em><b>Exclusive Maximum</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NUMBER_PROPERTIES__EXCLUSIVE_MAXIMUM = eINSTANCE.getNumberProperties_ExclusiveMaximum();

    /**
     * The meta object literal for the '{@link org.xtext.json.schema.draft7.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.json.schema.draft7.impl.TypeImpl
     * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__TYPES = eINSTANCE.getType_Types();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__TYPE = eINSTANCE.getType_Type();

    /**
     * The meta object literal for the '{@link org.xtext.json.schema.draft7.impl.ObjectPropertiesImpl <em>Object Properties</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.json.schema.draft7.impl.ObjectPropertiesImpl
     * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getObjectProperties()
     * @generated
     */
    EClass OBJECT_PROPERTIES = eINSTANCE.getObjectProperties();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT_PROPERTIES__PROPERTIES = eINSTANCE.getObjectProperties_Properties();

    /**
     * The meta object literal for the '<em><b>Required Properties</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT_PROPERTIES__REQUIRED_PROPERTIES = eINSTANCE.getObjectProperties_RequiredProperties();

    /**
     * The meta object literal for the '{@link org.xtext.json.schema.draft7.impl.RequiredPropertiesImpl <em>Required Properties</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.json.schema.draft7.impl.RequiredPropertiesImpl
     * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getRequiredProperties()
     * @generated
     */
    EClass REQUIRED_PROPERTIES = eINSTANCE.getRequiredProperties();

    /**
     * The meta object literal for the '<em><b>Required Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQUIRED_PROPERTIES__REQUIRED_PROPERTIES = eINSTANCE.getRequiredProperties_RequiredProperties();

    /**
     * The meta object literal for the '{@link org.xtext.json.schema.draft7.impl.RequiredPropertiesNameImpl <em>Required Properties Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.json.schema.draft7.impl.RequiredPropertiesNameImpl
     * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getRequiredPropertiesName()
     * @generated
     */
    EClass REQUIRED_PROPERTIES_NAME = eINSTANCE.getRequiredPropertiesName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REQUIRED_PROPERTIES_NAME__NAME = eINSTANCE.getRequiredPropertiesName_Name();

    /**
     * The meta object literal for the '{@link org.xtext.json.schema.draft7.impl.PropertiesImpl <em>Properties</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.json.schema.draft7.impl.PropertiesImpl
     * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getProperties()
     * @generated
     */
    EClass PROPERTIES = eINSTANCE.getProperties();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTIES__PROPERTIES = eINSTANCE.getProperties_Properties();

    /**
     * The meta object literal for the '{@link org.xtext.json.schema.draft7.impl.PropertyImpl <em>Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.json.schema.draft7.impl.PropertyImpl
     * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getProperty()
     * @generated
     */
    EClass PROPERTY = eINSTANCE.getProperty();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY__NAME = eINSTANCE.getProperty_Name();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY__PROPERTIES = eINSTANCE.getProperty_Properties();

    /**
     * The meta object literal for the '{@link org.xtext.json.schema.draft7.impl.StringPropertiesImpl <em>String Properties</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.json.schema.draft7.impl.StringPropertiesImpl
     * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getStringProperties()
     * @generated
     */
    EClass STRING_PROPERTIES = eINSTANCE.getStringProperties();

    /**
     * The meta object literal for the '<em><b>Length</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STRING_PROPERTIES__LENGTH = eINSTANCE.getStringProperties_Length();

    /**
     * The meta object literal for the '<em><b>Pattern</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STRING_PROPERTIES__PATTERN = eINSTANCE.getStringProperties_Pattern();

    /**
     * The meta object literal for the '{@link org.xtext.json.schema.draft7.impl.LengthImpl <em>Length</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.json.schema.draft7.impl.LengthImpl
     * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getLength()
     * @generated
     */
    EClass LENGTH = eINSTANCE.getLength();

    /**
     * The meta object literal for the '<em><b>Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LENGTH__LENGTH = eINSTANCE.getLength_Length();

    /**
     * The meta object literal for the '{@link org.xtext.json.schema.draft7.impl.PatternImpl <em>Pattern</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.json.schema.draft7.impl.PatternImpl
     * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getPattern()
     * @generated
     */
    EClass PATTERN = eINSTANCE.getPattern();

    /**
     * The meta object literal for the '<em><b>Pattern</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATTERN__PATTERN = eINSTANCE.getPattern_Pattern();

    /**
     * The meta object literal for the '{@link org.xtext.json.schema.draft7.impl.MultiplesImpl <em>Multiples</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.json.schema.draft7.impl.MultiplesImpl
     * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getMultiples()
     * @generated
     */
    EClass MULTIPLES = eINSTANCE.getMultiples();

    /**
     * The meta object literal for the '<em><b>Multiple Of</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTIPLES__MULTIPLE_OF = eINSTANCE.getMultiples_MultipleOf();

    /**
     * The meta object literal for the '{@link org.xtext.json.schema.draft7.impl.MinimumImpl <em>Minimum</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.json.schema.draft7.impl.MinimumImpl
     * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getMinimum()
     * @generated
     */
    EClass MINIMUM = eINSTANCE.getMinimum();

    /**
     * The meta object literal for the '<em><b>Minimum</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MINIMUM__MINIMUM = eINSTANCE.getMinimum_Minimum();

    /**
     * The meta object literal for the '{@link org.xtext.json.schema.draft7.impl.ExclusiveMinimumImpl <em>Exclusive Minimum</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.json.schema.draft7.impl.ExclusiveMinimumImpl
     * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getExclusiveMinimum()
     * @generated
     */
    EClass EXCLUSIVE_MINIMUM = eINSTANCE.getExclusiveMinimum();

    /**
     * The meta object literal for the '<em><b>Exclusive Minimum</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXCLUSIVE_MINIMUM__EXCLUSIVE_MINIMUM = eINSTANCE.getExclusiveMinimum_ExclusiveMinimum();

    /**
     * The meta object literal for the '{@link org.xtext.json.schema.draft7.impl.MaximumImpl <em>Maximum</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.json.schema.draft7.impl.MaximumImpl
     * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getMaximum()
     * @generated
     */
    EClass MAXIMUM = eINSTANCE.getMaximum();

    /**
     * The meta object literal for the '<em><b>Maximum</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAXIMUM__MAXIMUM = eINSTANCE.getMaximum_Maximum();

    /**
     * The meta object literal for the '{@link org.xtext.json.schema.draft7.impl.ExclusiveMaximumImpl <em>Exclusive Maximum</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.json.schema.draft7.impl.ExclusiveMaximumImpl
     * @see org.xtext.json.schema.draft7.impl.Draft7PackageImpl#getExclusiveMaximum()
     * @generated
     */
    EClass EXCLUSIVE_MAXIMUM = eINSTANCE.getExclusiveMaximum();

    /**
     * The meta object literal for the '<em><b>Exclusive Maximum</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXCLUSIVE_MAXIMUM__EXCLUSIVE_MAXIMUM = eINSTANCE.getExclusiveMaximum_ExclusiveMaximum();

  }

} //Draft7Package
