/**
 * generated by Xtext 2.20.0
 */
package org.xtext.json.schema.draft7;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exclusive Minimum</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.json.schema.draft7.ExclusiveMinimum#getExclusiveMinimum <em>Exclusive Minimum</em>}</li>
 * </ul>
 *
 * @see org.xtext.json.schema.draft7.Draft7Package#getExclusiveMinimum()
 * @model
 * @generated
 */
public interface ExclusiveMinimum extends EObject
{
  /**
   * Returns the value of the '<em><b>Exclusive Minimum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exclusive Minimum</em>' attribute.
   * @see #setExclusiveMinimum(int)
   * @see org.xtext.json.schema.draft7.Draft7Package#getExclusiveMinimum_ExclusiveMinimum()
   * @model
   * @generated
   */
  int getExclusiveMinimum();

  /**
   * Sets the value of the '{@link org.xtext.json.schema.draft7.ExclusiveMinimum#getExclusiveMinimum <em>Exclusive Minimum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exclusive Minimum</em>' attribute.
   * @see #getExclusiveMinimum()
   * @generated
   */
  void setExclusiveMinimum(int value);

} // ExclusiveMinimum
