/**
 * generated by Xtext 2.20.0
 */
package org.xtext.json.schema.draft7;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exclusive Maximum</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.json.schema.draft7.ExclusiveMaximum#getExclusiveMaximum <em>Exclusive Maximum</em>}</li>
 * </ul>
 *
 * @see org.xtext.json.schema.draft7.Draft7Package#getExclusiveMaximum()
 * @model
 * @generated
 */
public interface ExclusiveMaximum extends EObject
{
  /**
   * Returns the value of the '<em><b>Exclusive Maximum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exclusive Maximum</em>' attribute.
   * @see #setExclusiveMaximum(int)
   * @see org.xtext.json.schema.draft7.Draft7Package#getExclusiveMaximum_ExclusiveMaximum()
   * @model
   * @generated
   */
  int getExclusiveMaximum();

  /**
   * Sets the value of the '{@link org.xtext.json.schema.draft7.ExclusiveMaximum#getExclusiveMaximum <em>Exclusive Maximum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exclusive Maximum</em>' attribute.
   * @see #getExclusiveMaximum()
   * @generated
   */
  void setExclusiveMaximum(int value);

} // ExclusiveMaximum
