/**
 * generated by Xtext 2.20.0
 */
package org.xtext.json.schema.draft7;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object Properties</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.json.schema.draft7.ObjectProperties#getProperties <em>Properties</em>}</li>
 *   <li>{@link org.xtext.json.schema.draft7.ObjectProperties#getRequiredProperties <em>Required Properties</em>}</li>
 * </ul>
 *
 * @see org.xtext.json.schema.draft7.Draft7Package#getObjectProperties()
 * @model
 * @generated
 */
public interface ObjectProperties extends JsonSchemaRoot
{
  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference.
   * @see #setProperties(Properties)
   * @see org.xtext.json.schema.draft7.Draft7Package#getObjectProperties_Properties()
   * @model containment="true"
   * @generated
   */
  Properties getProperties();

  /**
   * Sets the value of the '{@link org.xtext.json.schema.draft7.ObjectProperties#getProperties <em>Properties</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Properties</em>' containment reference.
   * @see #getProperties()
   * @generated
   */
  void setProperties(Properties value);

  /**
   * Returns the value of the '<em><b>Required Properties</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Required Properties</em>' containment reference.
   * @see #setRequiredProperties(RequiredProperties)
   * @see org.xtext.json.schema.draft7.Draft7Package#getObjectProperties_RequiredProperties()
   * @model containment="true"
   * @generated
   */
  RequiredProperties getRequiredProperties();

  /**
   * Sets the value of the '{@link org.xtext.json.schema.draft7.ObjectProperties#getRequiredProperties <em>Required Properties</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Required Properties</em>' containment reference.
   * @see #getRequiredProperties()
   * @generated
   */
  void setRequiredProperties(RequiredProperties value);

} // ObjectProperties
