/**
 * generated by Xtext 2.20.0
 */
package org.xtext.json.schema.draft7;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Required Properties</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.json.schema.draft7.RequiredProperties#getZuper <em>Zuper</em>}</li>
 * </ul>
 *
 * @see org.xtext.json.schema.draft7.Draft7Package#getRequiredProperties()
 * @model
 * @generated
 */
public interface RequiredProperties extends EObject
{
  /**
   * Returns the value of the '<em><b>Zuper</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Zuper</em>' reference.
   * @see #setZuper(JSONProperty)
   * @see org.xtext.json.schema.draft7.Draft7Package#getRequiredProperties_Zuper()
   * @model
   * @generated
   */
  JSONProperty getZuper();

  /**
   * Sets the value of the '{@link org.xtext.json.schema.draft7.RequiredProperties#getZuper <em>Zuper</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Zuper</em>' reference.
   * @see #getZuper()
   * @generated
   */
  void setZuper(JSONProperty value);

} // RequiredProperties
