/**
 * generated by Xtext 2.20.0
 */
package org.xtext.json.schema.draft7;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Required Properties</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.json.schema.draft7.RequiredProperties#getRequiredProperties <em>Required Properties</em>}</li>
 * </ul>
 *
 * @see org.xtext.json.schema.draft7.Draft7Package#getRequiredProperties()
 * @model
 * @generated
 */
public interface RequiredProperties extends EObject
{
  /**
   * Returns the value of the '<em><b>Required Properties</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.json.schema.draft7.RequiredPropertiesName}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Required Properties</em>' containment reference list.
   * @see org.xtext.json.schema.draft7.Draft7Package#getRequiredProperties_RequiredProperties()
   * @model containment="true"
   * @generated
   */
  EList<RequiredPropertiesName> getRequiredProperties();

} // RequiredProperties
