/**
 * generated by Xtext 2.20.0
 */
package org.xtext.json.schema.draft7;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Root</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.json.schema.draft7.Draft7Package#getRoot()
 * @model
 * @generated
 */
public interface Root extends EObject
{
} // Root
