/**
 * generated by Xtext 2.20.0
 */
package org.xtext.json.schema.draft7;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Properties</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.json.schema.draft7.StringProperties#getLength <em>Length</em>}</li>
 *   <li>{@link org.xtext.json.schema.draft7.StringProperties#getPattern <em>Pattern</em>}</li>
 * </ul>
 *
 * @see org.xtext.json.schema.draft7.Draft7Package#getStringProperties()
 * @model
 * @generated
 */
public interface StringProperties extends JsonSchemaRoot
{
  /**
   * Returns the value of the '<em><b>Length</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Length</em>' containment reference.
   * @see #setLength(Length)
   * @see org.xtext.json.schema.draft7.Draft7Package#getStringProperties_Length()
   * @model containment="true"
   * @generated
   */
  Length getLength();

  /**
   * Sets the value of the '{@link org.xtext.json.schema.draft7.StringProperties#getLength <em>Length</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Length</em>' containment reference.
   * @see #getLength()
   * @generated
   */
  void setLength(Length value);

  /**
   * Returns the value of the '<em><b>Pattern</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pattern</em>' containment reference.
   * @see #setPattern(Pattern)
   * @see org.xtext.json.schema.draft7.Draft7Package#getStringProperties_Pattern()
   * @model containment="true"
   * @generated
   */
  Pattern getPattern();

  /**
   * Sets the value of the '{@link org.xtext.json.schema.draft7.StringProperties#getPattern <em>Pattern</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pattern</em>' containment reference.
   * @see #getPattern()
   * @generated
   */
  void setPattern(Pattern value);

} // StringProperties
