/*
 * generated by Xtext 2.20.0
 */
package org.xtext.json.schema.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.json.schema.ui.internal.SchemaActivator;

public class Draft7UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SchemaActivator.getInstance().getInjector("org.xtext.json.schema.Draft7");
	}

}
