/*
 * generated by Xtext 2.20.0
 */
package org.xtext.json.schema.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.json.schema.ide.contentassist.antlr.internal.InternalDraft7Parser;
import org.xtext.json.schema.services.Draft7GrammarAccess;

public class Draft7Parser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(Draft7GrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, Draft7GrammarAccess grammarAccess) {
			builder.put(grammarAccess.getRootAccess().getAlternatives(), "rule__Root__Alternatives");
			builder.put(grammarAccess.getTypeAccess().getAlternatives_2(), "rule__Type__Alternatives_2");
			builder.put(grammarAccess.getJsonTypesAccess().getAlternatives(), "rule__JsonTypes__Alternatives");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getModelAccess().getGroup_1(), "rule__Model__Group_1__0");
			builder.put(grammarAccess.getRootAccess().getGroup_0(), "rule__Root__Group_0__0");
			builder.put(grammarAccess.getRootAccess().getGroup_1(), "rule__Root__Group_1__0");
			builder.put(grammarAccess.getRootAccess().getGroup_2(), "rule__Root__Group_2__0");
			builder.put(grammarAccess.getRootAccess().getGroup_3(), "rule__Root__Group_3__0");
			builder.put(grammarAccess.getRootAccess().getGroup_4(), "rule__Root__Group_4__0");
			builder.put(grammarAccess.getRootAccess().getGroup_5(), "rule__Root__Group_5__0");
			builder.put(grammarAccess.getRootAccess().getGroup_6(), "rule__Root__Group_6__0");
			builder.put(grammarAccess.getRequiredPropertiesAccess().getGroup(), "rule__RequiredProperties__Group__0");
			builder.put(grammarAccess.getJSONPropertiesAccess().getGroup(), "rule__JSONProperties__Group__0");
			builder.put(grammarAccess.getJSONPropertyAccess().getGroup(), "rule__JSONProperty__Group__0");
			builder.put(grammarAccess.getTypeAccess().getGroup(), "rule__Type__Group__0");
			builder.put(grammarAccess.getTypeAccess().getGroup_2_0(), "rule__Type__Group_2_0__0");
			builder.put(grammarAccess.getMultiplesAccess().getGroup(), "rule__Multiples__Group__0");
			builder.put(grammarAccess.getMinimumAccess().getGroup(), "rule__Minimum__Group__0");
			builder.put(grammarAccess.getExclusiveMinimumAccess().getGroup(), "rule__ExclusiveMinimum__Group__0");
			builder.put(grammarAccess.getMaximumAccess().getGroup(), "rule__Maximum__Group__0");
			builder.put(grammarAccess.getExclusiveMaximumAccess().getGroup(), "rule__ExclusiveMaximum__Group__0");
			builder.put(grammarAccess.getLengthAccess().getGroup(), "rule__Length__Group__0");
			builder.put(grammarAccess.getModelAccess().getRootAssignment_1_0(), "rule__Model__RootAssignment_1_0");
			builder.put(grammarAccess.getRequiredPropertiesAccess().getZuperAssignment_3(), "rule__RequiredProperties__ZuperAssignment_3");
			builder.put(grammarAccess.getJSONPropertiesAccess().getPropertiesAssignment_4(), "rule__JSONProperties__PropertiesAssignment_4");
			builder.put(grammarAccess.getJSONPropertyAccess().getNameAssignment_0(), "rule__JSONProperty__NameAssignment_0");
			builder.put(grammarAccess.getJSONPropertyAccess().getPropertyAssignment_3(), "rule__JSONProperty__PropertyAssignment_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private Draft7GrammarAccess grammarAccess;

	@Override
	protected InternalDraft7Parser createParser() {
		InternalDraft7Parser result = new InternalDraft7Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public Draft7GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Draft7GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
